export default {
  pubKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4kHDWpwMcELUWnFPseP9
hoG0Gysfv77egglJ1NHj5zbCxrYKvFAD/POeGzO9CHdoKvi3TIaTWYTRKvLJtFyc
zpEPni2F+6f7yOFl7ueREV4sZHzNr/Hem03AcToUygJibwZpM6erSnrWKmPcGzZg
RXUG5l7LqhhzRVmvRo9b10AChNo/ehuSdbCLbgRCJNsaFkVIHf43wsLSEkbPsUs4
yvMi/BlMfiJIBa5tY9/TWs9VZ5t+9EK6oX3wnKqXJ1pUSDRbMSKtlBf0BEmMzC3R
kNP2lOKpuWpDPcW042rhDcJvZDlikeFPtVC1KSFMbtIun/wMBlBPdrvlhOwoFyJT
+QIDAQAB
-----END PUBLIC KEY-----`
}